[CLI] Completed functionality. Neither fully test-covered, nor polished.

diff --git a/Command Line Interface/lightshow-cli b/Command Line Interface/lightshow-cli
--- a/Command Line Interface/lightshow-cli
+++ b/Command Line Interface/lightshow-cli
@@ -1,58 +1,62 @@
 #!/bin/bash
 
-# TODO: Unfinished
-# http://www.linusakesson.net/programming/tty/index.php
-# https://stackoverflow.com/questions/8632586
-# https://learn.sparkfun.com/tutorials/terminal-basics/tips-and-tricks
-
-
-# This script...
+# This script provides the main interface for interacting with the command line utilities used for
+# configuring the behaviour of the Arduino Light Show.
 #
-# Arguments:
-# * <sub-command>, possible values:
-#  ** uninstall
-#  ** get-configuration
-#  ** apply-configuration
-#  ** configure-thresholds
-# * <sub-command dependant arguments>, possible values:
-#  ** uninstall: none
-#  ** get-configuration: <.ino file>
-#  ** apply-configuration: <configuration file> <.ino file>
-#  ** configure-thresholds: none
+# Arguments: *see <utility file: error messages: "lightshow-cli: Usage:">*
 #
-#
+# Return status:
+# 1 on incorrect usage, otherwise $? of the given subcommand
 
 
 #-Preliminaries---------------------------------#
 
 
-# Gets the directory of this script.
-dot=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
+# CLI-SUPPORTING-FILES-FOLDER
+readonly cli_supporting_files_folder="."
+
+# Imports CLI utilities.
+. "$cli_supporting_files_folder/Libraries/utilities.sh"
+. "$cli_supporting_files_folder/Libraries/constants.sh"
 
 
 #-Constants-------------------------------------#
 
 
-# CLI-SUPPORTING-FILES-FOLDER
-readonly cli_supporting_files_folder="$dot"
-readonly subcommand=$1; shift
+# The function wrapping all constant-declarations for this script.
+function declare_constants {
+   # Gets the location of the folder holding the program file(s).
+   readonly program_folder="../$cli_supporting_files_folder/`location_of_ --repo-program-directory`"
+   # Gets the program file, which should be the only file in the program-folder ending in ".ino".
+   readonly program_file="$program_folder/`ls -1 "$program_folder" | egrep '\.ino$'`"
 
-
-#-Functions-------------------------------------#
-
-
-function explain_usage {
-   # TODO: Implement
-   return 0
+   # Binds the subcommand passed as first argument.
+   readonly subcommand=$1
 }
 
 
 #-Main------------------------------------------#
 
+
+declare_constants "$@"
+# Shifts the given arguments to be passable to the subcommand.
+shift
+
+# Runs the script corresponding to the given subcommand, or prints and error message and returns on
+# failure if the given subcommand was invalid.
 case "$subcommand" in
-   uninstall)            "$cli_supporting_files_folder/Installation/uninstaller.sh" "$@" ;;
-   get-configuration)    "$cli_supporting_files_folder/Scripts/threshold_configuration.sh" "$@" ;;
-   apply-configuration)  "$cli_supporting_files_folder/Scripts/apply_configuration.sh" "$@" ;;
-   configure-thresholds) "$cli_supporting_files_folder/Scripts/configure_thresholds.sh" "$@" ;;
-   *)                    explain_usage ;;
+   uninstall)
+      "$cli_supporting_files_folder/uninstaller.sh" "$@" ;;
+   arduino-trait)
+      "$cli_supporting_files_folder/Scripts/arduino_trait.sh" "$@" ;;
+   get-configuration)
+      "$cli_supporting_files_folder/Scripts/threshold_configuration.sh" "$@" ;;
+   apply-configuration)
+      "$cli_supporting_files_folder/Scripts/apply_configuration.sh" "$@" ;;
+   push-program)
+      "$cli_supporting_files_folder/Scripts/push_program.sh" "$@" ;;
+   configure-thresholds)
+      "$cli_supporting_files_folder/Scripts/configure_thresholds.sh" "$@" ;;
+   *)
+      echo -e "`message_for_ --lcli-usage`"; exit 1 ;;
 esac
